#!/bin/bash

find ../ -name *.gcda

echo "Copying files to the correct locations for correct gcov analysis"
cp -R ../src/* ./src/
cp -R ../src/details/* ./src/details/
cp -R ../src/httpserver/* ./src/httpserver/
cp -R ../test/* ./test/
cp -R ../test/integ/* ./test/integ/
cp -R ../test/unit/* ./test/unit/

echo "Sending json report"
for filename in `find . | egrep '\.cpp'`; 
do 
  gcov -n -o . $filename > /dev/null; 
done

codecov
