/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class HttpUtils {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public HttpUtils(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(HttpUtils obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libjavawebserver_frameworkJNI.delete_HttpUtils(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static int getHttp_continue() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_continue_get();
  }

  public static int getHttp_switching_protocol() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_switching_protocol_get();
  }

  public static int getHttp_processing() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_processing_get();
  }

  public static int getHttp_ok() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_ok_get();
  }

  public static int getHttp_created() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_created_get();
  }

  public static int getHttp_accepted() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_accepted_get();
  }

  public static int getHttp_non_authoritative_information() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_non_authoritative_information_get();
  }

  public static int getHttp_no_content() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_no_content_get();
  }

  public static int getHttp_reset_content() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_reset_content_get();
  }

  public static int getHttp_partial_content() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_partial_content_get();
  }

  public static int getHttp_multi_status() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_multi_status_get();
  }

  public static int getHttp_multiple_choices() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_multiple_choices_get();
  }

  public static int getHttp_moved_permanently() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_moved_permanently_get();
  }

  public static int getHttp_found() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_found_get();
  }

  public static int getHttp_see_other() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_see_other_get();
  }

  public static int getHttp_not_modified() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_not_modified_get();
  }

  public static int getHttp_use_proxy() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_use_proxy_get();
  }

  public static int getHttp_switch_proxy() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_switch_proxy_get();
  }

  public static int getHttp_temporary_redirect() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_temporary_redirect_get();
  }

  public static int getHttp_bad_request() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_bad_request_get();
  }

  public static int getHttp_unauthorized() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_unauthorized_get();
  }

  public static int getHttp_payment_required() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_payment_required_get();
  }

  public static int getHttp_forbidden() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_forbidden_get();
  }

  public static int getHttp_not_found() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_not_found_get();
  }

  public static int getHttp_method_not_allowed() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_method_not_allowed_get();
  }

  public static int getHttp_method_not_acceptable() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_method_not_acceptable_get();
  }

  public static int getHttp_proxy_authentication_required() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_proxy_authentication_required_get();
  }

  public static int getHttp_request_timeout() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_request_timeout_get();
  }

  public static int getHttp_conflict() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_conflict_get();
  }

  public static int getHttp_gone() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_gone_get();
  }

  public static int getHttp_length_required() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_length_required_get();
  }

  public static int getHttp_precondition_failed() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_precondition_failed_get();
  }

  public static int getHttp_request_entity_too_large() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_request_entity_too_large_get();
  }

  public static int getHttp_request_uri_too_long() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_request_uri_too_long_get();
  }

  public static int getHttp_unsupported_media_type() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_unsupported_media_type_get();
  }

  public static int getHttp_requested_range_not_satisfiable() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_requested_range_not_satisfiable_get();
  }

  public static int getHttp_expectation_failed() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_expectation_failed_get();
  }

  public static int getHttp_unprocessable_entity() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_unprocessable_entity_get();
  }

  public static int getHttp_locked() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_locked_get();
  }

  public static int getHttp_failed_dependency() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_failed_dependency_get();
  }

  public static int getHttp_unordered_collection() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_unordered_collection_get();
  }

  public static int getHttp_upgrade_required() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_upgrade_required_get();
  }

  public static int getHttp_retry_with() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_retry_with_get();
  }

  public static int getHttp_internal_server_error() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_internal_server_error_get();
  }

  public static int getHttp_not_implemented() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_not_implemented_get();
  }

  public static int getHttp_bad_gateway() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_bad_gateway_get();
  }

  public static int getHttp_service_unavailable() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_service_unavailable_get();
  }

  public static int getHttp_gateway_timeout() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_gateway_timeout_get();
  }

  public static int getHttp_version_not_supported() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_version_not_supported_get();
  }

  public static int getHttp_variant_also_negotiated() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_variant_also_negotiated_get();
  }

  public static int getHttp_insufficient_storage() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_insufficient_storage_get();
  }

  public static int getHttp_bandwidth_limit_exceeded() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_bandwidth_limit_exceeded_get();
  }

  public static int getHttp_not_extended() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_not_extended_get();
  }

  public static String getHttp_header_accept() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_accept_get();
  }

  public static String getHttp_header_accept_charset() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_accept_charset_get();
  }

  public static String getHttp_header_accept_encoding() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_accept_encoding_get();
  }

  public static String getHttp_header_accept_language() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_accept_language_get();
  }

  public static String getHttp_header_accept_ranges() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_accept_ranges_get();
  }

  public static String getHttp_header_age() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_age_get();
  }

  public static String getHttp_header_allow() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_allow_get();
  }

  public static String getHttp_header_authorization() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_authorization_get();
  }

  public static String getHttp_header_cache_control() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_cache_control_get();
  }

  public static String getHttp_header_connection() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_connection_get();
  }

  public static String getHttp_header_content_encoding() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_content_encoding_get();
  }

  public static String getHttp_header_content_language() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_content_language_get();
  }

  public static String getHttp_header_content_length() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_content_length_get();
  }

  public static String getHttp_header_content_location() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_content_location_get();
  }

  public static String getHttp_header_content_md5() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_content_md5_get();
  }

  public static String getHttp_header_content_range() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_content_range_get();
  }

  public static String getHttp_header_content_type() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_content_type_get();
  }

  public static String getHttp_header_date() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_date_get();
  }

  public static String getHttp_header_etag() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_etag_get();
  }

  public static String getHttp_header_expect() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_expect_get();
  }

  public static String getHttp_header_expires() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_expires_get();
  }

  public static String getHttp_header_from() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_from_get();
  }

  public static String getHttp_header_host() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_host_get();
  }

  public static String getHttp_header_if_match() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_if_match_get();
  }

  public static String getHttp_header_if_modified_since() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_if_modified_since_get();
  }

  public static String getHttp_header_if_none_match() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_if_none_match_get();
  }

  public static String getHttp_header_if_range() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_if_range_get();
  }

  public static String getHttp_header_if_unmodified_since() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_if_unmodified_since_get();
  }

  public static String getHttp_header_last_modified() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_last_modified_get();
  }

  public static String getHttp_header_location() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_location_get();
  }

  public static String getHttp_header_max_forwards() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_max_forwards_get();
  }

  public static String getHttp_header_pragma() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_pragma_get();
  }

  public static String getHttp_header_proxy_authenticate() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_proxy_authenticate_get();
  }

  public static String getHttp_header_proxy_authentication() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_proxy_authentication_get();
  }

  public static String getHttp_header_range() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_range_get();
  }

  public static String getHttp_header_referer() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_referer_get();
  }

  public static String getHttp_header_retry_after() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_retry_after_get();
  }

  public static String getHttp_header_server() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_server_get();
  }

  public static String getHttp_header_te() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_te_get();
  }

  public static String getHttp_header_trailer() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_trailer_get();
  }

  public static String getHttp_header_transfer_encoding() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_transfer_encoding_get();
  }

  public static String getHttp_header_upgrade() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_upgrade_get();
  }

  public static String getHttp_header_user_agent() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_user_agent_get();
  }

  public static String getHttp_header_vary() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_vary_get();
  }

  public static String getHttp_header_via() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_via_get();
  }

  public static String getHttp_header_warning() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_warning_get();
  }

  public static String getHttp_header_www_authenticate() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_header_www_authenticate_get();
  }

  public static String getHttp_version_1_0() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_version_1_0_get();
  }

  public static String getHttp_version_1_1() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_version_1_1_get();
  }

  public static String getHttp_method_connect() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_method_connect_get();
  }

  public static String getHttp_method_delete() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_method_delete_get();
  }

  public static String getHttp_method_head() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_method_head_get();
  }

  public static String getHttp_method_get() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_method_get_get();
  }

  public static String getHttp_method_options() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_method_options_get();
  }

  public static String getHttp_method_post() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_method_post_get();
  }

  public static String getHttp_method_put() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_method_put_get();
  }

  public static String getHttp_method_trace() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_method_trace_get();
  }

  public static String getHttp_post_encoding_form_urlencoded() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_post_encoding_form_urlencoded_get();
  }

  public static String getHttp_post_encoding_multipart_formdata() {
    return libjavawebserver_frameworkJNI.HttpUtils_http_post_encoding_multipart_formdata_get();
  }

  public static StringVector tokenizeUrl(String arg0, String separator) {
    return new StringVector(libjavawebserver_frameworkJNI.HttpUtils_tokenizeUrl__SWIG_0(arg0, separator), true);
  }

  public static StringVector tokenizeUrl(String arg0) {
    return new StringVector(libjavawebserver_frameworkJNI.HttpUtils_tokenizeUrl__SWIG_1(arg0), true);
  }

  public static String standardizeUrl(String arg0) {
    return libjavawebserver_frameworkJNI.HttpUtils_standardizeUrl(arg0);
  }

  public HttpUtils() {
    this(libjavawebserver_frameworkJNI.new_HttpUtils(), true);
  }

  public final static class CredType_T {
    public final static HttpUtils.CredType_T NONE = new HttpUtils.CredType_T("NONE", -1);
    public final static HttpUtils.CredType_T CERTIFICATE = new HttpUtils.CredType_T("CERTIFICATE", GNUTLS_CRD_CERTIFICATE);
    public final static HttpUtils.CredType_T ANON = new HttpUtils.CredType_T("ANON", GNUTLS_CRD_ANON);
    public final static HttpUtils.CredType_T SRP = new HttpUtils.CredType_T("SRP", GNUTLS_CRD_SRP);
    public final static HttpUtils.CredType_T PSK = new HttpUtils.CredType_T("PSK", GNUTLS_CRD_PSK);
    public final static HttpUtils.CredType_T IA = new HttpUtils.CredType_T("IA", GNUTLS_CRD_IA);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static CredType_T swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + CredType_T.class + " with value " + swigValue);
    }

    private CredType_T(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private CredType_T(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private CredType_T(String swigName, CredType_T swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static CredType_T[] swigValues = { NONE, CERTIFICATE, ANON, SRP, PSK, IA };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
