/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class HttpEndpoint {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public HttpEndpoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(HttpEndpoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libjavawebserver_frameworkJNI.delete_HttpEndpoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HttpEndpoint(boolean family) {
    this(libjavawebserver_frameworkJNI.new_HttpEndpoint__SWIG_0(family), true);
  }

  public HttpEndpoint() {
    this(libjavawebserver_frameworkJNI.new_HttpEndpoint__SWIG_1(), true);
  }

  public HttpEndpoint(String url, boolean family, boolean registration) {
    this(libjavawebserver_frameworkJNI.new_HttpEndpoint__SWIG_2(url, family, registration), true);
  }

  public HttpEndpoint(String url, boolean family) {
    this(libjavawebserver_frameworkJNI.new_HttpEndpoint__SWIG_3(url, family), true);
  }

  public HttpEndpoint(String url) {
    this(libjavawebserver_frameworkJNI.new_HttpEndpoint__SWIG_4(url), true);
  }

  public boolean match(HttpEndpoint url) {
    return libjavawebserver_frameworkJNI.HttpEndpoint_match(swigCPtr, this, HttpEndpoint.getCPtr(url), url);
  }

  public StringVector get_url_pars() {
    return new StringVector(libjavawebserver_frameworkJNI.HttpEndpoint_get_url_pars(swigCPtr, this), true);
  }

  public StringVector get_url_pieces() {
    return new StringVector(libjavawebserver_frameworkJNI.HttpEndpoint_get_url_pieces(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_int_t get_chunk_positions() {
    return new SWIGTYPE_p_std__vectorT_int_t(libjavawebserver_frameworkJNI.HttpEndpoint_get_chunk_positions(swigCPtr, this), true);
  }

}
