/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class HttpRequest {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public HttpRequest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(HttpRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libjavawebserver_frameworkJNI.delete_HttpRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HttpRequest() {
    this(libjavawebserver_frameworkJNI.new_HttpRequest__SWIG_0(), true);
  }

  public HttpRequest(HttpRequest arg0) {
    this(libjavawebserver_frameworkJNI.new_HttpRequest__SWIG_1(HttpRequest.getCPtr(arg0), arg0), true);
  }

  public String getUser() {
    return libjavawebserver_frameworkJNI.HttpRequest_getUser(swigCPtr, this);
  }

  public String getPass() {
    return libjavawebserver_frameworkJNI.HttpRequest_getPass(swigCPtr, this);
  }

  public String getPath() {
    return libjavawebserver_frameworkJNI.HttpRequest_getPath(swigCPtr, this);
  }

  public StringVector getPathPieces() {
    return new StringVector(libjavawebserver_frameworkJNI.HttpRequest_getPathPieces(swigCPtr, this), true);
  }

  public String getMethod() {
    return libjavawebserver_frameworkJNI.HttpRequest_getMethod(swigCPtr, this);
  }

  public SWIGTYPE_p_std__mapT_std__string_std__string_t getHeaders() {
    return new SWIGTYPE_p_std__mapT_std__string_std__string_t(libjavawebserver_frameworkJNI.HttpRequest_getHeaders(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__mapT_std__string_std__string_t getArgs() {
    return new SWIGTYPE_p_std__mapT_std__string_std__string_t(libjavawebserver_frameworkJNI.HttpRequest_getArgs(swigCPtr, this), true);
  }

  public String getHeader(String arg0) {
    return libjavawebserver_frameworkJNI.HttpRequest_getHeader(swigCPtr, this, arg0);
  }

  public String getArg(String arg0) {
    return libjavawebserver_frameworkJNI.HttpRequest_getArg(swigCPtr, this, arg0);
  }

  public String getContent() {
    return libjavawebserver_frameworkJNI.HttpRequest_getContent(swigCPtr, this);
  }

  public void setHeader(String arg0, String arg1) {
    libjavawebserver_frameworkJNI.HttpRequest_setHeader(swigCPtr, this, arg0, arg1);
  }

  public void setArg(String arg0, String arg1) {
    libjavawebserver_frameworkJNI.HttpRequest_setArg(swigCPtr, this, arg0, arg1);
  }

  public void setContent(String arg0) {
    libjavawebserver_frameworkJNI.HttpRequest_setContent(swigCPtr, this, arg0);
  }

  public void growContent(String arg0, long size) {
    libjavawebserver_frameworkJNI.HttpRequest_growContent(swigCPtr, this, arg0, size);
  }

  public void setPath(String arg0) {
    libjavawebserver_frameworkJNI.HttpRequest_setPath(swigCPtr, this, arg0);
  }

  public void setMethod(String arg0) {
    libjavawebserver_frameworkJNI.HttpRequest_setMethod(swigCPtr, this, arg0);
  }

  public void removeHeader(String arg0) {
    libjavawebserver_frameworkJNI.HttpRequest_removeHeader(swigCPtr, this, arg0);
  }

  public void setHeaders(SWIGTYPE_p_std__mapT_std__string_std__string_t arg0) {
    libjavawebserver_frameworkJNI.HttpRequest_setHeaders(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_std__string_t.getCPtr(arg0));
  }

  public void setArgs(SWIGTYPE_p_std__mapT_std__string_std__string_t arg0) {
    libjavawebserver_frameworkJNI.HttpRequest_setArgs(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_std__string_t.getCPtr(arg0));
  }

  public void setUser(String arg0) {
    libjavawebserver_frameworkJNI.HttpRequest_setUser(swigCPtr, this, arg0);
  }

  public void setPass(String arg0) {
    libjavawebserver_frameworkJNI.HttpRequest_setPass(swigCPtr, this, arg0);
  }

}
