/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class libjavawebserver_frameworkJNI {
  public final static native long new_StringVector__SWIG_0();
  public final static native long new_StringVector__SWIG_1(long jarg1);
  public final static native long StringVector_size(long jarg1, StringVector jarg1_);
  public final static native long StringVector_capacity(long jarg1, StringVector jarg1_);
  public final static native void StringVector_reserve(long jarg1, StringVector jarg1_, long jarg2);
  public final static native boolean StringVector_isEmpty(long jarg1, StringVector jarg1_);
  public final static native void StringVector_clear(long jarg1, StringVector jarg1_);
  public final static native void StringVector_add(long jarg1, StringVector jarg1_, String jarg2);
  public final static native String StringVector_get(long jarg1, StringVector jarg1_, int jarg2);
  public final static native void StringVector_set(long jarg1, StringVector jarg1_, int jarg2, String jarg3);
  public final static native void delete_StringVector(long jarg1);
  public final static native int HttpUtils_http_continue_get();
  public final static native int HttpUtils_http_switching_protocol_get();
  public final static native int HttpUtils_http_processing_get();
  public final static native int HttpUtils_http_ok_get();
  public final static native int HttpUtils_http_created_get();
  public final static native int HttpUtils_http_accepted_get();
  public final static native int HttpUtils_http_non_authoritative_information_get();
  public final static native int HttpUtils_http_no_content_get();
  public final static native int HttpUtils_http_reset_content_get();
  public final static native int HttpUtils_http_partial_content_get();
  public final static native int HttpUtils_http_multi_status_get();
  public final static native int HttpUtils_http_multiple_choices_get();
  public final static native int HttpUtils_http_moved_permanently_get();
  public final static native int HttpUtils_http_found_get();
  public final static native int HttpUtils_http_see_other_get();
  public final static native int HttpUtils_http_not_modified_get();
  public final static native int HttpUtils_http_use_proxy_get();
  public final static native int HttpUtils_http_switch_proxy_get();
  public final static native int HttpUtils_http_temporary_redirect_get();
  public final static native int HttpUtils_http_bad_request_get();
  public final static native int HttpUtils_http_unauthorized_get();
  public final static native int HttpUtils_http_payment_required_get();
  public final static native int HttpUtils_http_forbidden_get();
  public final static native int HttpUtils_http_not_found_get();
  public final static native int HttpUtils_http_method_not_allowed_get();
  public final static native int HttpUtils_http_method_not_acceptable_get();
  public final static native int HttpUtils_http_proxy_authentication_required_get();
  public final static native int HttpUtils_http_request_timeout_get();
  public final static native int HttpUtils_http_conflict_get();
  public final static native int HttpUtils_http_gone_get();
  public final static native int HttpUtils_http_length_required_get();
  public final static native int HttpUtils_http_precondition_failed_get();
  public final static native int HttpUtils_http_request_entity_too_large_get();
  public final static native int HttpUtils_http_request_uri_too_long_get();
  public final static native int HttpUtils_http_unsupported_media_type_get();
  public final static native int HttpUtils_http_requested_range_not_satisfiable_get();
  public final static native int HttpUtils_http_expectation_failed_get();
  public final static native int HttpUtils_http_unprocessable_entity_get();
  public final static native int HttpUtils_http_locked_get();
  public final static native int HttpUtils_http_failed_dependency_get();
  public final static native int HttpUtils_http_unordered_collection_get();
  public final static native int HttpUtils_http_upgrade_required_get();
  public final static native int HttpUtils_http_retry_with_get();
  public final static native int HttpUtils_http_internal_server_error_get();
  public final static native int HttpUtils_http_not_implemented_get();
  public final static native int HttpUtils_http_bad_gateway_get();
  public final static native int HttpUtils_http_service_unavailable_get();
  public final static native int HttpUtils_http_gateway_timeout_get();
  public final static native int HttpUtils_http_version_not_supported_get();
  public final static native int HttpUtils_http_variant_also_negotiated_get();
  public final static native int HttpUtils_http_insufficient_storage_get();
  public final static native int HttpUtils_http_bandwidth_limit_exceeded_get();
  public final static native int HttpUtils_http_not_extended_get();
  public final static native String HttpUtils_http_header_accept_get();
  public final static native String HttpUtils_http_header_accept_charset_get();
  public final static native String HttpUtils_http_header_accept_encoding_get();
  public final static native String HttpUtils_http_header_accept_language_get();
  public final static native String HttpUtils_http_header_accept_ranges_get();
  public final static native String HttpUtils_http_header_age_get();
  public final static native String HttpUtils_http_header_allow_get();
  public final static native String HttpUtils_http_header_authorization_get();
  public final static native String HttpUtils_http_header_cache_control_get();
  public final static native String HttpUtils_http_header_connection_get();
  public final static native String HttpUtils_http_header_content_encoding_get();
  public final static native String HttpUtils_http_header_content_language_get();
  public final static native String HttpUtils_http_header_content_length_get();
  public final static native String HttpUtils_http_header_content_location_get();
  public final static native String HttpUtils_http_header_content_md5_get();
  public final static native String HttpUtils_http_header_content_range_get();
  public final static native String HttpUtils_http_header_content_type_get();
  public final static native String HttpUtils_http_header_date_get();
  public final static native String HttpUtils_http_header_etag_get();
  public final static native String HttpUtils_http_header_expect_get();
  public final static native String HttpUtils_http_header_expires_get();
  public final static native String HttpUtils_http_header_from_get();
  public final static native String HttpUtils_http_header_host_get();
  public final static native String HttpUtils_http_header_if_match_get();
  public final static native String HttpUtils_http_header_if_modified_since_get();
  public final static native String HttpUtils_http_header_if_none_match_get();
  public final static native String HttpUtils_http_header_if_range_get();
  public final static native String HttpUtils_http_header_if_unmodified_since_get();
  public final static native String HttpUtils_http_header_last_modified_get();
  public final static native String HttpUtils_http_header_location_get();
  public final static native String HttpUtils_http_header_max_forwards_get();
  public final static native String HttpUtils_http_header_pragma_get();
  public final static native String HttpUtils_http_header_proxy_authenticate_get();
  public final static native String HttpUtils_http_header_proxy_authentication_get();
  public final static native String HttpUtils_http_header_range_get();
  public final static native String HttpUtils_http_header_referer_get();
  public final static native String HttpUtils_http_header_retry_after_get();
  public final static native String HttpUtils_http_header_server_get();
  public final static native String HttpUtils_http_header_te_get();
  public final static native String HttpUtils_http_header_trailer_get();
  public final static native String HttpUtils_http_header_transfer_encoding_get();
  public final static native String HttpUtils_http_header_upgrade_get();
  public final static native String HttpUtils_http_header_user_agent_get();
  public final static native String HttpUtils_http_header_vary_get();
  public final static native String HttpUtils_http_header_via_get();
  public final static native String HttpUtils_http_header_warning_get();
  public final static native String HttpUtils_http_header_www_authenticate_get();
  public final static native String HttpUtils_http_version_1_0_get();
  public final static native String HttpUtils_http_version_1_1_get();
  public final static native String HttpUtils_http_method_connect_get();
  public final static native String HttpUtils_http_method_delete_get();
  public final static native String HttpUtils_http_method_head_get();
  public final static native String HttpUtils_http_method_get_get();
  public final static native String HttpUtils_http_method_options_get();
  public final static native String HttpUtils_http_method_post_get();
  public final static native String HttpUtils_http_method_put_get();
  public final static native String HttpUtils_http_method_trace_get();
  public final static native String HttpUtils_http_post_encoding_form_urlencoded_get();
  public final static native String HttpUtils_http_post_encoding_multipart_formdata_get();
  public final static native long HttpUtils_tokenizeUrl__SWIG_0(String jarg1, String jarg2);
  public final static native long HttpUtils_tokenizeUrl__SWIG_1(String jarg1);
  public final static native String HttpUtils_standardizeUrl(String jarg1);
  public final static native long new_HttpUtils();
  public final static native void delete_HttpUtils(long jarg1);
  public final static native long new_ArgComparator();
  public final static native void delete_ArgComparator(long jarg1);
  public final static native long new_HttpEndpoint__SWIG_0(boolean jarg1);
  public final static native long new_HttpEndpoint__SWIG_1();
  public final static native long new_HttpEndpoint__SWIG_2(String jarg1, boolean jarg2, boolean jarg3);
  public final static native long new_HttpEndpoint__SWIG_3(String jarg1, boolean jarg2);
  public final static native long new_HttpEndpoint__SWIG_4(String jarg1);
  public final static native boolean HttpEndpoint_match(long jarg1, HttpEndpoint jarg1_, long jarg2, HttpEndpoint jarg2_);
  public final static native long HttpEndpoint_get_url_pars(long jarg1, HttpEndpoint jarg1_);
  public final static native long HttpEndpoint_get_url_pieces(long jarg1, HttpEndpoint jarg1_);
  public final static native long HttpEndpoint_get_chunk_positions(long jarg1, HttpEndpoint jarg1_);
  public final static native void delete_HttpEndpoint(long jarg1);
  public final static native long new_HttpRequest__SWIG_0();
  public final static native long new_HttpRequest__SWIG_1(long jarg1, HttpRequest jarg1_);
  public final static native String HttpRequest_getUser(long jarg1, HttpRequest jarg1_);
  public final static native String HttpRequest_getPass(long jarg1, HttpRequest jarg1_);
  public final static native String HttpRequest_getPath(long jarg1, HttpRequest jarg1_);
  public final static native long HttpRequest_getPathPieces(long jarg1, HttpRequest jarg1_);
  public final static native String HttpRequest_getMethod(long jarg1, HttpRequest jarg1_);
  public final static native long HttpRequest_getHeaders(long jarg1, HttpRequest jarg1_);
  public final static native long HttpRequest_getArgs(long jarg1, HttpRequest jarg1_);
  public final static native String HttpRequest_getHeader(long jarg1, HttpRequest jarg1_, String jarg2);
  public final static native String HttpRequest_getArg(long jarg1, HttpRequest jarg1_, String jarg2);
  public final static native String HttpRequest_getContent(long jarg1, HttpRequest jarg1_);
  public final static native void HttpRequest_setHeader(long jarg1, HttpRequest jarg1_, String jarg2, String jarg3);
  public final static native void HttpRequest_setArg(long jarg1, HttpRequest jarg1_, String jarg2, String jarg3);
  public final static native void HttpRequest_setContent(long jarg1, HttpRequest jarg1_, String jarg2);
  public final static native void HttpRequest_growContent(long jarg1, HttpRequest jarg1_, String jarg2, long jarg3);
  public final static native void HttpRequest_setPath(long jarg1, HttpRequest jarg1_, String jarg2);
  public final static native void HttpRequest_setMethod(long jarg1, HttpRequest jarg1_, String jarg2);
  public final static native void HttpRequest_removeHeader(long jarg1, HttpRequest jarg1_, String jarg2);
  public final static native void HttpRequest_setHeaders(long jarg1, HttpRequest jarg1_, long jarg2);
  public final static native void HttpRequest_setArgs(long jarg1, HttpRequest jarg1_, long jarg2);
  public final static native void HttpRequest_setUser(long jarg1, HttpRequest jarg1_, String jarg2);
  public final static native void HttpRequest_setPass(long jarg1, HttpRequest jarg1_, String jarg2);
  public final static native void delete_HttpRequest(long jarg1);
  public final static native long new_HttpResponse__SWIG_0();
  public final static native long new_HttpResponse__SWIG_1(String jarg1, int jarg2, int jarg3);
  public final static native long new_HttpResponse__SWIG_2(String jarg1, int jarg2);
  public final static native long new_HttpResponse__SWIG_3(long jarg1, HttpResponse jarg1_);
  public final static native String HttpResponse_getContent(long jarg1, HttpResponse jarg1_);
  public final static native void HttpResponse_setContent(long jarg1, HttpResponse jarg1_, String jarg2);
  public final static native String HttpResponse_getHeader(long jarg1, HttpResponse jarg1_, String jarg2);
  public final static native String HttpResponse_getFooter(long jarg1, HttpResponse jarg1_, String jarg2);
  public final static native void HttpResponse_setHeader(long jarg1, HttpResponse jarg1_, String jarg2, String jarg3);
  public final static native void HttpResponse_setFooter(long jarg1, HttpResponse jarg1_, String jarg2, String jarg3);
  public final static native void HttpResponse_setContentType(long jarg1, HttpResponse jarg1_, String jarg2);
  public final static native void HttpResponse_removeHeader(long jarg1, HttpResponse jarg1_, String jarg2);
  public final static native long HttpResponse_getHeaders(long jarg1, HttpResponse jarg1_);
  public final static native long HttpResponse_getFooters(long jarg1, HttpResponse jarg1_);
  public final static native void HttpResponse_setHeaders(long jarg1, HttpResponse jarg1_, long jarg2);
  public final static native void HttpResponse_setFooters(long jarg1, HttpResponse jarg1_, long jarg2);
  public final static native void HttpResponse_setResponseCode(long jarg1, HttpResponse jarg1_, int jarg2);
  public final static native int HttpResponse_getResponseCode(long jarg1, HttpResponse jarg1_);
  public final static native void delete_HttpResponse(long jarg1);
  public final static native long new_HttpResource();
  public final static native void delete_HttpResource(long jarg1);
  public final static native long HttpResource_render(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_renderSwigExplicitHttpResource(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_404(long jarg1, HttpResource jarg1_);
  public final static native long HttpResource_render_404SwigExplicitHttpResource(long jarg1, HttpResource jarg1_);
  public final static native long HttpResource_render_500(long jarg1, HttpResource jarg1_);
  public final static native long HttpResource_render_500SwigExplicitHttpResource(long jarg1, HttpResource jarg1_);
  public final static native long HttpResource_render_405(long jarg1, HttpResource jarg1_);
  public final static native long HttpResource_render_405SwigExplicitHttpResource(long jarg1, HttpResource jarg1_);
  public final static native long HttpResource_render_GET(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_GETSwigExplicitHttpResource(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_POST(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_POSTSwigExplicitHttpResource(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_PUT(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_PUTSwigExplicitHttpResource(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_HEAD(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_HEADSwigExplicitHttpResource(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_DELETE(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_DELETESwigExplicitHttpResource(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_TRACE(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_TRACESwigExplicitHttpResource(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_OPTIONS(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_OPTIONSSwigExplicitHttpResource(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_CONNECT(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_render_CONNECTSwigExplicitHttpResource(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_routeRequest(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long HttpResource_routeRequestSwigExplicitHttpResource(long jarg1, HttpResource jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native void HttpResource_setAllowing(long jarg1, HttpResource jarg1_, String jarg2, boolean jarg3);
  public final static native void HttpResource_allowAll(long jarg1, HttpResource jarg1_);
  public final static native void HttpResource_disallowAll(long jarg1, HttpResource jarg1_);
  public final static native boolean HttpResource_isAllowed(long jarg1, HttpResource jarg1_, String jarg2);
  public final static native void HttpResource_director_connect(HttpResource obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void HttpResource_change_ownership(HttpResource obj, long cptr, boolean take_or_release);
  public final static native long new_LoggingDelegate();
  public final static native void delete_LoggingDelegate(long jarg1);
  public final static native void LoggingDelegate_log_access(long jarg1, LoggingDelegate jarg1_, String jarg2);
  public final static native void LoggingDelegate_log_error(long jarg1, LoggingDelegate jarg1_, String jarg2);
  public final static native long new_RequestValidator();
  public final static native void delete_RequestValidator(long jarg1);
  public final static native boolean RequestValidator_validate(long jarg1, RequestValidator jarg1_, String jarg2);
  public final static native long new_Unescaper();
  public final static native void delete_Unescaper(long jarg1);
  public final static native void Unescaper_unescape(long jarg1, Unescaper jarg1_, String jarg2);
  public final static native long new_Webserver__SWIG_0(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7, LoggingDelegate jarg7_, long jarg8, RequestValidator jarg8_, long jarg9, Unescaper jarg9_, int jarg10, String jarg11, String jarg12, String jarg13, String jarg14, int jarg15, String jarg16, int jarg17);
  public final static native long new_Webserver__SWIG_1(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7, LoggingDelegate jarg7_, long jarg8, RequestValidator jarg8_, long jarg9, Unescaper jarg9_, int jarg10, String jarg11, String jarg12, String jarg13, String jarg14, int jarg15, String jarg16);
  public final static native long new_Webserver__SWIG_2(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7, LoggingDelegate jarg7_, long jarg8, RequestValidator jarg8_, long jarg9, Unescaper jarg9_, int jarg10, String jarg11, String jarg12, String jarg13, String jarg14, int jarg15);
  public final static native long new_Webserver__SWIG_3(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7, LoggingDelegate jarg7_, long jarg8, RequestValidator jarg8_, long jarg9, Unescaper jarg9_, int jarg10, String jarg11, String jarg12, String jarg13, String jarg14);
  public final static native long new_Webserver__SWIG_4(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7, LoggingDelegate jarg7_, long jarg8, RequestValidator jarg8_, long jarg9, Unescaper jarg9_, int jarg10, String jarg11, String jarg12, String jarg13);
  public final static native long new_Webserver__SWIG_5(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7, LoggingDelegate jarg7_, long jarg8, RequestValidator jarg8_, long jarg9, Unescaper jarg9_, int jarg10, String jarg11, String jarg12);
  public final static native long new_Webserver__SWIG_6(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7, LoggingDelegate jarg7_, long jarg8, RequestValidator jarg8_, long jarg9, Unescaper jarg9_, int jarg10, String jarg11);
  public final static native long new_Webserver__SWIG_7(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7, LoggingDelegate jarg7_, long jarg8, RequestValidator jarg8_, long jarg9, Unescaper jarg9_, int jarg10);
  public final static native long new_Webserver__SWIG_8(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7, LoggingDelegate jarg7_, long jarg8, RequestValidator jarg8_, long jarg9, Unescaper jarg9_);
  public final static native long new_Webserver__SWIG_9(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7, LoggingDelegate jarg7_, long jarg8, RequestValidator jarg8_);
  public final static native long new_Webserver__SWIG_10(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, long jarg7, LoggingDelegate jarg7_);
  public final static native long new_Webserver__SWIG_11(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6);
  public final static native long new_Webserver__SWIG_12(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5);
  public final static native long new_Webserver__SWIG_13(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native long new_Webserver__SWIG_14(int jarg1, int jarg2, int jarg3);
  public final static native long new_Webserver__SWIG_15(int jarg1, int jarg2);
  public final static native long new_Webserver__SWIG_16(int jarg1);
  public final static native long new_Webserver__SWIG_17();
  public final static native void delete_Webserver(long jarg1);
  public final static native boolean Webserver_start__SWIG_0(long jarg1, Webserver jarg1_, boolean jarg2);
  public final static native boolean Webserver_start__SWIG_1(long jarg1, Webserver jarg1_);
  public final static native boolean Webserver_stop(long jarg1, Webserver jarg1_);
  public final static native boolean Webserver_isRunning(long jarg1, Webserver jarg1_);
  public final static native void Webserver_registerResource__SWIG_0(long jarg1, Webserver jarg1_, String jarg2, long jarg3, HttpResource jarg3_, boolean jarg4);
  public final static native void Webserver_registerResource__SWIG_1(long jarg1, Webserver jarg1_, String jarg2, long jarg3, HttpResource jarg3_);
  public final static native void Webserver_sweetKill(long jarg1, Webserver jarg1_);
  public final static native void ModdedRequest_pp_set(long jarg1, ModdedRequest jarg1_, long jarg2);
  public final static native long ModdedRequest_pp_get(long jarg1, ModdedRequest jarg1_);
  public final static native void ModdedRequest_completeUri_set(long jarg1, ModdedRequest jarg1_, long jarg2);
  public final static native long ModdedRequest_completeUri_get(long jarg1, ModdedRequest jarg1_);
  public final static native void ModdedRequest_dhr_set(long jarg1, ModdedRequest jarg1_, long jarg2, HttpRequest jarg2_);
  public final static native long ModdedRequest_dhr_get(long jarg1, ModdedRequest jarg1_);
  public final static native void ModdedRequest_second_set(long jarg1, ModdedRequest jarg1_, boolean jarg2);
  public final static native boolean ModdedRequest_second_get(long jarg1, ModdedRequest jarg1_);
  public final static native long new_ModdedRequest();
  public final static native void delete_ModdedRequest(long jarg1);

  public static long SwigDirector_HttpResource_render(HttpResource self, long arg0) {
    return HttpResponse.getCPtr(self.render(new HttpRequest(arg0, false)));
  }
  public static long SwigDirector_HttpResource_render_404(HttpResource self) {
    return HttpResponse.getCPtr(self.render_404());
  }
  public static long SwigDirector_HttpResource_render_500(HttpResource self) {
    return HttpResponse.getCPtr(self.render_500());
  }
  public static long SwigDirector_HttpResource_render_405(HttpResource self) {
    return HttpResponse.getCPtr(self.render_405());
  }
  public static long SwigDirector_HttpResource_render_GET(HttpResource self, long arg0) {
    return HttpResponse.getCPtr(self.render_GET(new HttpRequest(arg0, false)));
  }
  public static long SwigDirector_HttpResource_render_POST(HttpResource self, long arg0) {
    return HttpResponse.getCPtr(self.render_POST(new HttpRequest(arg0, false)));
  }
  public static long SwigDirector_HttpResource_render_PUT(HttpResource self, long arg0) {
    return HttpResponse.getCPtr(self.render_PUT(new HttpRequest(arg0, false)));
  }
  public static long SwigDirector_HttpResource_render_HEAD(HttpResource self, long arg0) {
    return HttpResponse.getCPtr(self.render_HEAD(new HttpRequest(arg0, false)));
  }
  public static long SwigDirector_HttpResource_render_DELETE(HttpResource self, long arg0) {
    return HttpResponse.getCPtr(self.render_DELETE(new HttpRequest(arg0, false)));
  }
  public static long SwigDirector_HttpResource_render_TRACE(HttpResource self, long arg0) {
    return HttpResponse.getCPtr(self.render_TRACE(new HttpRequest(arg0, false)));
  }
  public static long SwigDirector_HttpResource_render_OPTIONS(HttpResource self, long arg0) {
    return HttpResponse.getCPtr(self.render_OPTIONS(new HttpRequest(arg0, false)));
  }
  public static long SwigDirector_HttpResource_render_CONNECT(HttpResource self, long arg0) {
    return HttpResponse.getCPtr(self.render_CONNECT(new HttpRequest(arg0, false)));
  }
  public static long SwigDirector_HttpResource_routeRequest(HttpResource self, long arg0) {
    return HttpResponse.getCPtr(self.routeRequest(new HttpRequest(arg0, false)));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
