/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface libjavawebserver_frameworkConstants {
  public final static String NOT_FOUND_ERROR = "{\"description\":\"NOT FOUND\"}";
  public final static String METHOD_ERROR = "{\"description\":\"METHOD NOT ALLOWED\"}";
  public final static String NOT_METHOD_ERROR = "{\"description\":\"METHOD NOT ACCEPTABLE\"}";
  public final static String GENERIC_ERROR = "{\"description\":\"INTERNAL ERROR\"}";
  public final static int DEFAULT_DROP_WS_PORT = 9898;
  public final static int DEFAULT_DROP_WS_TIMEOUT = 180;
}
