/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class LoggingDelegate {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public LoggingDelegate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(LoggingDelegate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libjavawebserver_frameworkJNI.delete_LoggingDelegate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LoggingDelegate() {
    this(libjavawebserver_frameworkJNI.new_LoggingDelegate(), true);
  }

  public void log_access(String arg0) {
    libjavawebserver_frameworkJNI.LoggingDelegate_log_access(swigCPtr, this, arg0);
  }

  public void log_error(String arg0) {
    libjavawebserver_frameworkJNI.LoggingDelegate_log_error(swigCPtr, this, arg0);
  }

}
