/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class LoggingDelegate {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LoggingDelegate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LoggingDelegate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libhttpserver_javaJNI.delete_LoggingDelegate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LoggingDelegate() {
    this(libhttpserver_javaJNI.new_LoggingDelegate(), true);
  }

  public void log_access(String s) {
    libhttpserver_javaJNI.LoggingDelegate_log_access(swigCPtr, this, s);
  }

  public void log_error(String s) {
    libhttpserver_javaJNI.LoggingDelegate_log_error(swigCPtr, this, s);
  }

}
