/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ModdedRequest {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ModdedRequest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModdedRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libhttpserver_javaJNI.delete_ModdedRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPp(SWIGTYPE_p_MHD_PostProcessor value) {
    libhttpserver_javaJNI.ModdedRequest_pp_set(swigCPtr, this, SWIGTYPE_p_MHD_PostProcessor.getCPtr(value));
  }

  public SWIGTYPE_p_MHD_PostProcessor getPp() {
    long cPtr = libhttpserver_javaJNI.ModdedRequest_pp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_MHD_PostProcessor(cPtr, false);
  }

  public void setCompleteUri(SWIGTYPE_p_std__string value) {
    libhttpserver_javaJNI.ModdedRequest_completeUri_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getCompleteUri() {
    long cPtr = libhttpserver_javaJNI.ModdedRequest_completeUri_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public void setDhr(SWIGTYPE_p_httpserver__HttpRequest value) {
    libhttpserver_javaJNI.ModdedRequest_dhr_set(swigCPtr, this, SWIGTYPE_p_httpserver__HttpRequest.getCPtr(value));
  }

  public SWIGTYPE_p_httpserver__HttpRequest getDhr() {
    long cPtr = libhttpserver_javaJNI.ModdedRequest_dhr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_httpserver__HttpRequest(cPtr, false);
  }

  public void setWs(Webserver value) {
    libhttpserver_javaJNI.ModdedRequest_ws_set(swigCPtr, this, Webserver.getCPtr(value), value);
  }

  public Webserver getWs() {
    long cPtr = libhttpserver_javaJNI.ModdedRequest_ws_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Webserver(cPtr, false);
  }

  public void setSecond(boolean value) {
    libhttpserver_javaJNI.ModdedRequest_second_set(swigCPtr, this, value);
  }

  public boolean getSecond() {
    return libhttpserver_javaJNI.ModdedRequest_second_get(swigCPtr, this);
  }

  public ModdedRequest() {
    this(libhttpserver_javaJNI.new_ModdedRequest(), true);
  }

}
