/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class RequestValidator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RequestValidator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RequestValidator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libhttpserver_javaJNI.delete_RequestValidator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RequestValidator() {
    this(libhttpserver_javaJNI.new_RequestValidator(), true);
  }

  public boolean validate(String address) {
    return libhttpserver_javaJNI.RequestValidator_validate(swigCPtr, this, address);
  }

}
