/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Unescaper {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Unescaper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Unescaper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libhttpserver_javaJNI.delete_Unescaper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Unescaper() {
    this(libhttpserver_javaJNI.new_Unescaper(), true);
  }

  public void unescape(String s) {
    libhttpserver_javaJNI.Unescaper_unescape(swigCPtr, this, s);
  }

}
