/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Webserver {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Webserver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Webserver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libjavawebserver_frameworkJNI.delete_Webserver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit, LoggingDelegate logDelegate, RequestValidator validator, Unescaper unescaper, int maxThreadStackSize, String httpsMemKey, String httpsMemCert, String httpsMemTrust, String httpsPriorities, HttpUtils.CredType_T credType, String digestAuthRandom, int nonceNcSize) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_0(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit, LoggingDelegate.getCPtr(logDelegate), logDelegate, RequestValidator.getCPtr(validator), validator, Unescaper.getCPtr(unescaper), unescaper, maxThreadStackSize, httpsMemKey, httpsMemCert, httpsMemTrust, httpsPriorities, credType.swigValue(), digestAuthRandom, nonceNcSize), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit, LoggingDelegate logDelegate, RequestValidator validator, Unescaper unescaper, int maxThreadStackSize, String httpsMemKey, String httpsMemCert, String httpsMemTrust, String httpsPriorities, HttpUtils.CredType_T credType, String digestAuthRandom) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_1(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit, LoggingDelegate.getCPtr(logDelegate), logDelegate, RequestValidator.getCPtr(validator), validator, Unescaper.getCPtr(unescaper), unescaper, maxThreadStackSize, httpsMemKey, httpsMemCert, httpsMemTrust, httpsPriorities, credType.swigValue(), digestAuthRandom), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit, LoggingDelegate logDelegate, RequestValidator validator, Unescaper unescaper, int maxThreadStackSize, String httpsMemKey, String httpsMemCert, String httpsMemTrust, String httpsPriorities, HttpUtils.CredType_T credType) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_2(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit, LoggingDelegate.getCPtr(logDelegate), logDelegate, RequestValidator.getCPtr(validator), validator, Unescaper.getCPtr(unescaper), unescaper, maxThreadStackSize, httpsMemKey, httpsMemCert, httpsMemTrust, httpsPriorities, credType.swigValue()), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit, LoggingDelegate logDelegate, RequestValidator validator, Unescaper unescaper, int maxThreadStackSize, String httpsMemKey, String httpsMemCert, String httpsMemTrust, String httpsPriorities) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_3(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit, LoggingDelegate.getCPtr(logDelegate), logDelegate, RequestValidator.getCPtr(validator), validator, Unescaper.getCPtr(unescaper), unescaper, maxThreadStackSize, httpsMemKey, httpsMemCert, httpsMemTrust, httpsPriorities), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit, LoggingDelegate logDelegate, RequestValidator validator, Unescaper unescaper, int maxThreadStackSize, String httpsMemKey, String httpsMemCert, String httpsMemTrust) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_4(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit, LoggingDelegate.getCPtr(logDelegate), logDelegate, RequestValidator.getCPtr(validator), validator, Unescaper.getCPtr(unescaper), unescaper, maxThreadStackSize, httpsMemKey, httpsMemCert, httpsMemTrust), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit, LoggingDelegate logDelegate, RequestValidator validator, Unescaper unescaper, int maxThreadStackSize, String httpsMemKey, String httpsMemCert) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_5(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit, LoggingDelegate.getCPtr(logDelegate), logDelegate, RequestValidator.getCPtr(validator), validator, Unescaper.getCPtr(unescaper), unescaper, maxThreadStackSize, httpsMemKey, httpsMemCert), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit, LoggingDelegate logDelegate, RequestValidator validator, Unescaper unescaper, int maxThreadStackSize, String httpsMemKey) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_6(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit, LoggingDelegate.getCPtr(logDelegate), logDelegate, RequestValidator.getCPtr(validator), validator, Unescaper.getCPtr(unescaper), unescaper, maxThreadStackSize, httpsMemKey), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit, LoggingDelegate logDelegate, RequestValidator validator, Unescaper unescaper, int maxThreadStackSize) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_7(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit, LoggingDelegate.getCPtr(logDelegate), logDelegate, RequestValidator.getCPtr(validator), validator, Unescaper.getCPtr(unescaper), unescaper, maxThreadStackSize), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit, LoggingDelegate logDelegate, RequestValidator validator, Unescaper unescaper) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_8(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit, LoggingDelegate.getCPtr(logDelegate), logDelegate, RequestValidator.getCPtr(validator), validator, Unescaper.getCPtr(unescaper), unescaper), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit, LoggingDelegate logDelegate, RequestValidator validator) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_9(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit, LoggingDelegate.getCPtr(logDelegate), logDelegate, RequestValidator.getCPtr(validator), validator), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit, LoggingDelegate logDelegate) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_10(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit, LoggingDelegate.getCPtr(logDelegate), logDelegate), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout, int perIPConnectionLimit) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_11(port, maxThreads, maxConnections, memoryLimit, connectionTimeout, perIPConnectionLimit), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit, int connectionTimeout) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_12(port, maxThreads, maxConnections, memoryLimit, connectionTimeout), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections, int memoryLimit) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_13(port, maxThreads, maxConnections, memoryLimit), true);
  }

  public Webserver(int port, int maxThreads, int maxConnections) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_14(port, maxThreads, maxConnections), true);
  }

  public Webserver(int port, int maxThreads) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_15(port, maxThreads), true);
  }

  public Webserver(int port) {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_16(port), true);
  }

  public Webserver() {
    this(libjavawebserver_frameworkJNI.new_Webserver__SWIG_17(), true);
  }

  public boolean start(boolean blocking) {
    return libjavawebserver_frameworkJNI.Webserver_start__SWIG_0(swigCPtr, this, blocking);
  }

  public boolean start() {
    return libjavawebserver_frameworkJNI.Webserver_start__SWIG_1(swigCPtr, this);
  }

  public boolean stop() {
    return libjavawebserver_frameworkJNI.Webserver_stop(swigCPtr, this);
  }

  public boolean isRunning() {
    return libjavawebserver_frameworkJNI.Webserver_isRunning(swigCPtr, this);
  }

  public void registerResource(String resource, HttpResource http_resource, boolean family) {
    libjavawebserver_frameworkJNI.Webserver_registerResource__SWIG_0(swigCPtr, this, resource, HttpResource.getCPtr(http_resource), http_resource, family);
  }

  public void registerResource(String resource, HttpResource http_resource) {
    libjavawebserver_frameworkJNI.Webserver_registerResource__SWIG_1(swigCPtr, this, resource, HttpResource.getCPtr(http_resource), http_resource);
  }

  public void sweetKill() {
    libjavawebserver_frameworkJNI.Webserver_sweetKill(swigCPtr, this);
  }

}
