# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libpythonwebserver_framework', [dirname(__file__)])
        except ImportError:
            import _libpythonwebserver_framework
            return _libpythonwebserver_framework
        if fp is not None:
            try:
                _mod = imp.load_module('_libpythonwebserver_framework', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libpythonwebserver_framework = swig_import_helper()
    del swig_import_helper
else:
    import _libpythonwebserver_framework
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _libpythonwebserver_framework.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _libpythonwebserver_framework.SwigPyIterator_value(self)
    def incr(self, n = 1): return _libpythonwebserver_framework.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _libpythonwebserver_framework.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _libpythonwebserver_framework.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _libpythonwebserver_framework.SwigPyIterator_equal(self, *args)
    def copy(self): return _libpythonwebserver_framework.SwigPyIterator_copy(self)
    def next(self): return _libpythonwebserver_framework.SwigPyIterator_next(self)
    def __next__(self): return _libpythonwebserver_framework.SwigPyIterator___next__(self)
    def previous(self): return _libpythonwebserver_framework.SwigPyIterator_previous(self)
    def advance(self, *args): return _libpythonwebserver_framework.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _libpythonwebserver_framework.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _libpythonwebserver_framework.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _libpythonwebserver_framework.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _libpythonwebserver_framework.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _libpythonwebserver_framework.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _libpythonwebserver_framework.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _libpythonwebserver_framework.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _libpythonwebserver_framework.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _libpythonwebserver_framework.StringVector___nonzero__(self)
    def __bool__(self): return _libpythonwebserver_framework.StringVector___bool__(self)
    def __len__(self): return _libpythonwebserver_framework.StringVector___len__(self)
    def pop(self): return _libpythonwebserver_framework.StringVector_pop(self)
    def __getslice__(self, *args): return _libpythonwebserver_framework.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _libpythonwebserver_framework.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _libpythonwebserver_framework.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _libpythonwebserver_framework.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _libpythonwebserver_framework.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _libpythonwebserver_framework.StringVector___setitem__(self, *args)
    def append(self, *args): return _libpythonwebserver_framework.StringVector_append(self, *args)
    def empty(self): return _libpythonwebserver_framework.StringVector_empty(self)
    def size(self): return _libpythonwebserver_framework.StringVector_size(self)
    def clear(self): return _libpythonwebserver_framework.StringVector_clear(self)
    def swap(self, *args): return _libpythonwebserver_framework.StringVector_swap(self, *args)
    def get_allocator(self): return _libpythonwebserver_framework.StringVector_get_allocator(self)
    def begin(self): return _libpythonwebserver_framework.StringVector_begin(self)
    def end(self): return _libpythonwebserver_framework.StringVector_end(self)
    def rbegin(self): return _libpythonwebserver_framework.StringVector_rbegin(self)
    def rend(self): return _libpythonwebserver_framework.StringVector_rend(self)
    def pop_back(self): return _libpythonwebserver_framework.StringVector_pop_back(self)
    def erase(self, *args): return _libpythonwebserver_framework.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _libpythonwebserver_framework.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _libpythonwebserver_framework.StringVector_push_back(self, *args)
    def front(self): return _libpythonwebserver_framework.StringVector_front(self)
    def back(self): return _libpythonwebserver_framework.StringVector_back(self)
    def assign(self, *args): return _libpythonwebserver_framework.StringVector_assign(self, *args)
    def resize(self, *args): return _libpythonwebserver_framework.StringVector_resize(self, *args)
    def insert(self, *args): return _libpythonwebserver_framework.StringVector_insert(self, *args)
    def reserve(self, *args): return _libpythonwebserver_framework.StringVector_reserve(self, *args)
    def capacity(self): return _libpythonwebserver_framework.StringVector_capacity(self)
    __swig_destroy__ = _libpythonwebserver_framework.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _libpythonwebserver_framework.StringVector_swigregister
StringVector_swigregister(StringVector)

class StringPair(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringPair, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringPair, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _libpythonwebserver_framework.new_StringPair(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["first"] = _libpythonwebserver_framework.StringPair_first_set
    __swig_getmethods__["first"] = _libpythonwebserver_framework.StringPair_first_get
    if _newclass:first = _swig_property(_libpythonwebserver_framework.StringPair_first_get, _libpythonwebserver_framework.StringPair_first_set)
    __swig_setmethods__["second"] = _libpythonwebserver_framework.StringPair_second_set
    __swig_getmethods__["second"] = _libpythonwebserver_framework.StringPair_second_get
    if _newclass:second = _swig_property(_libpythonwebserver_framework.StringPair_second_get, _libpythonwebserver_framework.StringPair_second_set)
    def __len__(self): return 2
    def __repr__(self): return str((self.first, self.second))
    def __getitem__(self, index): 
      if not (index % 2): 
        return self.first
      else:
        return self.second
    def __setitem__(self, index, val):
      if not (index % 2): 
        self.first = val
      else:
        self.second = val
    __swig_destroy__ = _libpythonwebserver_framework.delete_StringPair
    __del__ = lambda self : None;
StringPair_swigregister = _libpythonwebserver_framework.StringPair_swigregister
StringPair_swigregister(StringPair)

class ArgVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ArgVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ArgVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _libpythonwebserver_framework.ArgVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _libpythonwebserver_framework.ArgVector___nonzero__(self)
    def __bool__(self): return _libpythonwebserver_framework.ArgVector___bool__(self)
    def __len__(self): return _libpythonwebserver_framework.ArgVector___len__(self)
    def pop(self): return _libpythonwebserver_framework.ArgVector_pop(self)
    def __getslice__(self, *args): return _libpythonwebserver_framework.ArgVector___getslice__(self, *args)
    def __setslice__(self, *args): return _libpythonwebserver_framework.ArgVector___setslice__(self, *args)
    def __delslice__(self, *args): return _libpythonwebserver_framework.ArgVector___delslice__(self, *args)
    def __delitem__(self, *args): return _libpythonwebserver_framework.ArgVector___delitem__(self, *args)
    def __getitem__(self, *args): return _libpythonwebserver_framework.ArgVector___getitem__(self, *args)
    def __setitem__(self, *args): return _libpythonwebserver_framework.ArgVector___setitem__(self, *args)
    def append(self, *args): return _libpythonwebserver_framework.ArgVector_append(self, *args)
    def empty(self): return _libpythonwebserver_framework.ArgVector_empty(self)
    def size(self): return _libpythonwebserver_framework.ArgVector_size(self)
    def clear(self): return _libpythonwebserver_framework.ArgVector_clear(self)
    def swap(self, *args): return _libpythonwebserver_framework.ArgVector_swap(self, *args)
    def get_allocator(self): return _libpythonwebserver_framework.ArgVector_get_allocator(self)
    def begin(self): return _libpythonwebserver_framework.ArgVector_begin(self)
    def end(self): return _libpythonwebserver_framework.ArgVector_end(self)
    def rbegin(self): return _libpythonwebserver_framework.ArgVector_rbegin(self)
    def rend(self): return _libpythonwebserver_framework.ArgVector_rend(self)
    def pop_back(self): return _libpythonwebserver_framework.ArgVector_pop_back(self)
    def erase(self, *args): return _libpythonwebserver_framework.ArgVector_erase(self, *args)
    def __init__(self, *args): 
        this = _libpythonwebserver_framework.new_ArgVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _libpythonwebserver_framework.ArgVector_push_back(self, *args)
    def front(self): return _libpythonwebserver_framework.ArgVector_front(self)
    def back(self): return _libpythonwebserver_framework.ArgVector_back(self)
    def assign(self, *args): return _libpythonwebserver_framework.ArgVector_assign(self, *args)
    def resize(self, *args): return _libpythonwebserver_framework.ArgVector_resize(self, *args)
    def insert(self, *args): return _libpythonwebserver_framework.ArgVector_insert(self, *args)
    def reserve(self, *args): return _libpythonwebserver_framework.ArgVector_reserve(self, *args)
    def capacity(self): return _libpythonwebserver_framework.ArgVector_capacity(self)
    __swig_destroy__ = _libpythonwebserver_framework.delete_ArgVector
    __del__ = lambda self : None;
ArgVector_swigregister = _libpythonwebserver_framework.ArgVector_swigregister
ArgVector_swigregister(ArgVector)

class HttpUtils(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HttpUtils, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HttpUtils, name)
    __repr__ = _swig_repr
    NONE = _libpythonwebserver_framework.HttpUtils_NONE
    CERTIFICATE = _libpythonwebserver_framework.HttpUtils_CERTIFICATE
    ANON = _libpythonwebserver_framework.HttpUtils_ANON
    SRP = _libpythonwebserver_framework.HttpUtils_SRP
    PSK = _libpythonwebserver_framework.HttpUtils_PSK
    IA = _libpythonwebserver_framework.HttpUtils_IA
    __swig_getmethods__["tokenizeUrl"] = lambda x: _libpythonwebserver_framework.HttpUtils_tokenizeUrl
    if _newclass:tokenizeUrl = staticmethod(_libpythonwebserver_framework.HttpUtils_tokenizeUrl)
    __swig_getmethods__["standardizeUrl"] = lambda x: _libpythonwebserver_framework.HttpUtils_standardizeUrl
    if _newclass:standardizeUrl = staticmethod(_libpythonwebserver_framework.HttpUtils_standardizeUrl)
    def __init__(self): 
        this = _libpythonwebserver_framework.new_HttpUtils()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libpythonwebserver_framework.delete_HttpUtils
    __del__ = lambda self : None;
HttpUtils_swigregister = _libpythonwebserver_framework.HttpUtils_swigregister
HttpUtils_swigregister(HttpUtils)
cvar = _libpythonwebserver_framework.cvar
HttpUtils.http_continue = _libpythonwebserver_framework.cvar.HttpUtils_http_continue
HttpUtils.http_switching_protocol = _libpythonwebserver_framework.cvar.HttpUtils_http_switching_protocol
HttpUtils.http_processing = _libpythonwebserver_framework.cvar.HttpUtils_http_processing
HttpUtils.http_ok = _libpythonwebserver_framework.cvar.HttpUtils_http_ok
HttpUtils.http_created = _libpythonwebserver_framework.cvar.HttpUtils_http_created
HttpUtils.http_accepted = _libpythonwebserver_framework.cvar.HttpUtils_http_accepted
HttpUtils.http_non_authoritative_information = _libpythonwebserver_framework.cvar.HttpUtils_http_non_authoritative_information
HttpUtils.http_no_content = _libpythonwebserver_framework.cvar.HttpUtils_http_no_content
HttpUtils.http_reset_content = _libpythonwebserver_framework.cvar.HttpUtils_http_reset_content
HttpUtils.http_partial_content = _libpythonwebserver_framework.cvar.HttpUtils_http_partial_content
HttpUtils.http_multi_status = _libpythonwebserver_framework.cvar.HttpUtils_http_multi_status
HttpUtils.http_multiple_choices = _libpythonwebserver_framework.cvar.HttpUtils_http_multiple_choices
HttpUtils.http_moved_permanently = _libpythonwebserver_framework.cvar.HttpUtils_http_moved_permanently
HttpUtils.http_found = _libpythonwebserver_framework.cvar.HttpUtils_http_found
HttpUtils.http_see_other = _libpythonwebserver_framework.cvar.HttpUtils_http_see_other
HttpUtils.http_not_modified = _libpythonwebserver_framework.cvar.HttpUtils_http_not_modified
HttpUtils.http_use_proxy = _libpythonwebserver_framework.cvar.HttpUtils_http_use_proxy
HttpUtils.http_switch_proxy = _libpythonwebserver_framework.cvar.HttpUtils_http_switch_proxy
HttpUtils.http_temporary_redirect = _libpythonwebserver_framework.cvar.HttpUtils_http_temporary_redirect
HttpUtils.http_bad_request = _libpythonwebserver_framework.cvar.HttpUtils_http_bad_request
HttpUtils.http_unauthorized = _libpythonwebserver_framework.cvar.HttpUtils_http_unauthorized
HttpUtils.http_payment_required = _libpythonwebserver_framework.cvar.HttpUtils_http_payment_required
HttpUtils.http_forbidden = _libpythonwebserver_framework.cvar.HttpUtils_http_forbidden
HttpUtils.http_not_found = _libpythonwebserver_framework.cvar.HttpUtils_http_not_found
HttpUtils.http_method_not_allowed = _libpythonwebserver_framework.cvar.HttpUtils_http_method_not_allowed
HttpUtils.http_method_not_acceptable = _libpythonwebserver_framework.cvar.HttpUtils_http_method_not_acceptable
HttpUtils.http_proxy_authentication_required = _libpythonwebserver_framework.cvar.HttpUtils_http_proxy_authentication_required
HttpUtils.http_request_timeout = _libpythonwebserver_framework.cvar.HttpUtils_http_request_timeout
HttpUtils.http_conflict = _libpythonwebserver_framework.cvar.HttpUtils_http_conflict
HttpUtils.http_gone = _libpythonwebserver_framework.cvar.HttpUtils_http_gone
HttpUtils.http_length_required = _libpythonwebserver_framework.cvar.HttpUtils_http_length_required
HttpUtils.http_precondition_failed = _libpythonwebserver_framework.cvar.HttpUtils_http_precondition_failed
HttpUtils.http_request_entity_too_large = _libpythonwebserver_framework.cvar.HttpUtils_http_request_entity_too_large
HttpUtils.http_request_uri_too_long = _libpythonwebserver_framework.cvar.HttpUtils_http_request_uri_too_long
HttpUtils.http_unsupported_media_type = _libpythonwebserver_framework.cvar.HttpUtils_http_unsupported_media_type
HttpUtils.http_requested_range_not_satisfiable = _libpythonwebserver_framework.cvar.HttpUtils_http_requested_range_not_satisfiable
HttpUtils.http_expectation_failed = _libpythonwebserver_framework.cvar.HttpUtils_http_expectation_failed
HttpUtils.http_unprocessable_entity = _libpythonwebserver_framework.cvar.HttpUtils_http_unprocessable_entity
HttpUtils.http_locked = _libpythonwebserver_framework.cvar.HttpUtils_http_locked
HttpUtils.http_failed_dependency = _libpythonwebserver_framework.cvar.HttpUtils_http_failed_dependency
HttpUtils.http_unordered_collection = _libpythonwebserver_framework.cvar.HttpUtils_http_unordered_collection
HttpUtils.http_upgrade_required = _libpythonwebserver_framework.cvar.HttpUtils_http_upgrade_required
HttpUtils.http_retry_with = _libpythonwebserver_framework.cvar.HttpUtils_http_retry_with
HttpUtils.http_internal_server_error = _libpythonwebserver_framework.cvar.HttpUtils_http_internal_server_error
HttpUtils.http_not_implemented = _libpythonwebserver_framework.cvar.HttpUtils_http_not_implemented
HttpUtils.http_bad_gateway = _libpythonwebserver_framework.cvar.HttpUtils_http_bad_gateway
HttpUtils.http_service_unavailable = _libpythonwebserver_framework.cvar.HttpUtils_http_service_unavailable
HttpUtils.http_gateway_timeout = _libpythonwebserver_framework.cvar.HttpUtils_http_gateway_timeout
HttpUtils.http_version_not_supported = _libpythonwebserver_framework.cvar.HttpUtils_http_version_not_supported
HttpUtils.http_variant_also_negotiated = _libpythonwebserver_framework.cvar.HttpUtils_http_variant_also_negotiated
HttpUtils.http_insufficient_storage = _libpythonwebserver_framework.cvar.HttpUtils_http_insufficient_storage
HttpUtils.http_bandwidth_limit_exceeded = _libpythonwebserver_framework.cvar.HttpUtils_http_bandwidth_limit_exceeded
HttpUtils.http_not_extended = _libpythonwebserver_framework.cvar.HttpUtils_http_not_extended
HttpUtils.http_header_accept = _libpythonwebserver_framework.cvar.HttpUtils_http_header_accept
HttpUtils.http_header_accept_charset = _libpythonwebserver_framework.cvar.HttpUtils_http_header_accept_charset
HttpUtils.http_header_accept_encoding = _libpythonwebserver_framework.cvar.HttpUtils_http_header_accept_encoding
HttpUtils.http_header_accept_language = _libpythonwebserver_framework.cvar.HttpUtils_http_header_accept_language
HttpUtils.http_header_accept_ranges = _libpythonwebserver_framework.cvar.HttpUtils_http_header_accept_ranges
HttpUtils.http_header_age = _libpythonwebserver_framework.cvar.HttpUtils_http_header_age
HttpUtils.http_header_allow = _libpythonwebserver_framework.cvar.HttpUtils_http_header_allow
HttpUtils.http_header_authorization = _libpythonwebserver_framework.cvar.HttpUtils_http_header_authorization
HttpUtils.http_header_cache_control = _libpythonwebserver_framework.cvar.HttpUtils_http_header_cache_control
HttpUtils.http_header_connection = _libpythonwebserver_framework.cvar.HttpUtils_http_header_connection
HttpUtils.http_header_content_encoding = _libpythonwebserver_framework.cvar.HttpUtils_http_header_content_encoding
HttpUtils.http_header_content_language = _libpythonwebserver_framework.cvar.HttpUtils_http_header_content_language
HttpUtils.http_header_content_length = _libpythonwebserver_framework.cvar.HttpUtils_http_header_content_length
HttpUtils.http_header_content_location = _libpythonwebserver_framework.cvar.HttpUtils_http_header_content_location
HttpUtils.http_header_content_md5 = _libpythonwebserver_framework.cvar.HttpUtils_http_header_content_md5
HttpUtils.http_header_content_range = _libpythonwebserver_framework.cvar.HttpUtils_http_header_content_range
HttpUtils.http_header_content_type = _libpythonwebserver_framework.cvar.HttpUtils_http_header_content_type
HttpUtils.http_header_date = _libpythonwebserver_framework.cvar.HttpUtils_http_header_date
HttpUtils.http_header_etag = _libpythonwebserver_framework.cvar.HttpUtils_http_header_etag
HttpUtils.http_header_expect = _libpythonwebserver_framework.cvar.HttpUtils_http_header_expect
HttpUtils.http_header_expires = _libpythonwebserver_framework.cvar.HttpUtils_http_header_expires
HttpUtils.http_header_from = _libpythonwebserver_framework.cvar.HttpUtils_http_header_from
HttpUtils.http_header_host = _libpythonwebserver_framework.cvar.HttpUtils_http_header_host
HttpUtils.http_header_if_match = _libpythonwebserver_framework.cvar.HttpUtils_http_header_if_match
HttpUtils.http_header_if_modified_since = _libpythonwebserver_framework.cvar.HttpUtils_http_header_if_modified_since
HttpUtils.http_header_if_none_match = _libpythonwebserver_framework.cvar.HttpUtils_http_header_if_none_match
HttpUtils.http_header_if_range = _libpythonwebserver_framework.cvar.HttpUtils_http_header_if_range
HttpUtils.http_header_if_unmodified_since = _libpythonwebserver_framework.cvar.HttpUtils_http_header_if_unmodified_since
HttpUtils.http_header_last_modified = _libpythonwebserver_framework.cvar.HttpUtils_http_header_last_modified
HttpUtils.http_header_location = _libpythonwebserver_framework.cvar.HttpUtils_http_header_location
HttpUtils.http_header_max_forwards = _libpythonwebserver_framework.cvar.HttpUtils_http_header_max_forwards
HttpUtils.http_header_pragma = _libpythonwebserver_framework.cvar.HttpUtils_http_header_pragma
HttpUtils.http_header_proxy_authenticate = _libpythonwebserver_framework.cvar.HttpUtils_http_header_proxy_authenticate
HttpUtils.http_header_proxy_authentication = _libpythonwebserver_framework.cvar.HttpUtils_http_header_proxy_authentication
HttpUtils.http_header_range = _libpythonwebserver_framework.cvar.HttpUtils_http_header_range
HttpUtils.http_header_referer = _libpythonwebserver_framework.cvar.HttpUtils_http_header_referer
HttpUtils.http_header_retry_after = _libpythonwebserver_framework.cvar.HttpUtils_http_header_retry_after
HttpUtils.http_header_server = _libpythonwebserver_framework.cvar.HttpUtils_http_header_server
HttpUtils.http_header_te = _libpythonwebserver_framework.cvar.HttpUtils_http_header_te
HttpUtils.http_header_trailer = _libpythonwebserver_framework.cvar.HttpUtils_http_header_trailer
HttpUtils.http_header_transfer_encoding = _libpythonwebserver_framework.cvar.HttpUtils_http_header_transfer_encoding
HttpUtils.http_header_upgrade = _libpythonwebserver_framework.cvar.HttpUtils_http_header_upgrade
HttpUtils.http_header_user_agent = _libpythonwebserver_framework.cvar.HttpUtils_http_header_user_agent
HttpUtils.http_header_vary = _libpythonwebserver_framework.cvar.HttpUtils_http_header_vary
HttpUtils.http_header_via = _libpythonwebserver_framework.cvar.HttpUtils_http_header_via
HttpUtils.http_header_warning = _libpythonwebserver_framework.cvar.HttpUtils_http_header_warning
HttpUtils.http_header_www_authenticate = _libpythonwebserver_framework.cvar.HttpUtils_http_header_www_authenticate
HttpUtils.http_version_1_0 = _libpythonwebserver_framework.cvar.HttpUtils_http_version_1_0
HttpUtils.http_version_1_1 = _libpythonwebserver_framework.cvar.HttpUtils_http_version_1_1
HttpUtils.http_method_connect = _libpythonwebserver_framework.cvar.HttpUtils_http_method_connect
HttpUtils.http_method_delete = _libpythonwebserver_framework.cvar.HttpUtils_http_method_delete
HttpUtils.http_method_head = _libpythonwebserver_framework.cvar.HttpUtils_http_method_head
HttpUtils.http_method_get = _libpythonwebserver_framework.cvar.HttpUtils_http_method_get
HttpUtils.http_method_options = _libpythonwebserver_framework.cvar.HttpUtils_http_method_options
HttpUtils.http_method_post = _libpythonwebserver_framework.cvar.HttpUtils_http_method_post
HttpUtils.http_method_put = _libpythonwebserver_framework.cvar.HttpUtils_http_method_put
HttpUtils.http_method_trace = _libpythonwebserver_framework.cvar.HttpUtils_http_method_trace
HttpUtils.http_post_encoding_form_urlencoded = _libpythonwebserver_framework.cvar.HttpUtils_http_post_encoding_form_urlencoded
HttpUtils.http_post_encoding_multipart_formdata = _libpythonwebserver_framework.cvar.HttpUtils_http_post_encoding_multipart_formdata

def HttpUtils_tokenizeUrl(*args):
  return _libpythonwebserver_framework.HttpUtils_tokenizeUrl(*args)
HttpUtils_tokenizeUrl = _libpythonwebserver_framework.HttpUtils_tokenizeUrl

def HttpUtils_standardizeUrl(*args):
  return _libpythonwebserver_framework.HttpUtils_standardizeUrl(*args)
HttpUtils_standardizeUrl = _libpythonwebserver_framework.HttpUtils_standardizeUrl

class HeaderComparator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HeaderComparator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HeaderComparator, name)
    __repr__ = _swig_repr
    def __call__(self, *args): return _libpythonwebserver_framework.HeaderComparator___call__(self, *args)
    def __init__(self): 
        this = _libpythonwebserver_framework.new_HeaderComparator()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libpythonwebserver_framework.delete_HeaderComparator
    __del__ = lambda self : None;
HeaderComparator_swigregister = _libpythonwebserver_framework.HeaderComparator_swigregister
HeaderComparator_swigregister(HeaderComparator)

class ArgComparator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ArgComparator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ArgComparator, name)
    __repr__ = _swig_repr
    def __call__(self, *args): return _libpythonwebserver_framework.ArgComparator___call__(self, *args)
    def __init__(self): 
        this = _libpythonwebserver_framework.new_ArgComparator()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libpythonwebserver_framework.delete_ArgComparator
    __del__ = lambda self : None;
ArgComparator_swigregister = _libpythonwebserver_framework.ArgComparator_swigregister
ArgComparator_swigregister(ArgComparator)


def generate_random_uuid():
  return _libpythonwebserver_framework.generate_random_uuid()
generate_random_uuid = _libpythonwebserver_framework.generate_random_uuid

def get_port(*args):
  return _libpythonwebserver_framework.get_port(*args)
get_port = _libpythonwebserver_framework.get_port

def http_unescape(*args):
  return _libpythonwebserver_framework.http_unescape(*args)
http_unescape = _libpythonwebserver_framework.http_unescape
class SQMHeaders(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SQMHeaders, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SQMHeaders, name)
    __repr__ = _swig_repr
    def iterator(self): return _libpythonwebserver_framework.SQMHeaders_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _libpythonwebserver_framework.SQMHeaders___nonzero__(self)
    def __bool__(self): return _libpythonwebserver_framework.SQMHeaders___bool__(self)
    def __len__(self): return _libpythonwebserver_framework.SQMHeaders___len__(self)
    def __iter__(self): return self.key_iterator()
    def iterkeys(self): return self.key_iterator()
    def itervalues(self): return self.value_iterator()
    def iteritems(self): return self.iterator()
    def __getitem__(self, *args): return _libpythonwebserver_framework.SQMHeaders___getitem__(self, *args)
    def __delitem__(self, *args): return _libpythonwebserver_framework.SQMHeaders___delitem__(self, *args)
    def has_key(self, *args): return _libpythonwebserver_framework.SQMHeaders_has_key(self, *args)
    def keys(self): return _libpythonwebserver_framework.SQMHeaders_keys(self)
    def values(self): return _libpythonwebserver_framework.SQMHeaders_values(self)
    def items(self): return _libpythonwebserver_framework.SQMHeaders_items(self)
    def __contains__(self, *args): return _libpythonwebserver_framework.SQMHeaders___contains__(self, *args)
    def key_iterator(self): return _libpythonwebserver_framework.SQMHeaders_key_iterator(self)
    def value_iterator(self): return _libpythonwebserver_framework.SQMHeaders_value_iterator(self)
    def __setitem__(self, *args): return _libpythonwebserver_framework.SQMHeaders___setitem__(self, *args)
    def asdict(self): return _libpythonwebserver_framework.SQMHeaders_asdict(self)
    def __init__(self, *args): 
        this = _libpythonwebserver_framework.new_SQMHeaders(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _libpythonwebserver_framework.SQMHeaders_empty(self)
    def size(self): return _libpythonwebserver_framework.SQMHeaders_size(self)
    def clear(self): return _libpythonwebserver_framework.SQMHeaders_clear(self)
    def swap(self, *args): return _libpythonwebserver_framework.SQMHeaders_swap(self, *args)
    def get_allocator(self): return _libpythonwebserver_framework.SQMHeaders_get_allocator(self)
    def begin(self): return _libpythonwebserver_framework.SQMHeaders_begin(self)
    def end(self): return _libpythonwebserver_framework.SQMHeaders_end(self)
    def rbegin(self): return _libpythonwebserver_framework.SQMHeaders_rbegin(self)
    def rend(self): return _libpythonwebserver_framework.SQMHeaders_rend(self)
    def count(self, *args): return _libpythonwebserver_framework.SQMHeaders_count(self, *args)
    def erase(self, *args): return _libpythonwebserver_framework.SQMHeaders_erase(self, *args)
    def find(self, *args): return _libpythonwebserver_framework.SQMHeaders_find(self, *args)
    def lower_bound(self, *args): return _libpythonwebserver_framework.SQMHeaders_lower_bound(self, *args)
    def upper_bound(self, *args): return _libpythonwebserver_framework.SQMHeaders_upper_bound(self, *args)
    def getHeader(self, *args): return _libpythonwebserver_framework.SQMHeaders_getHeader(self, *args)
    __swig_destroy__ = _libpythonwebserver_framework.delete_SQMHeaders
    __del__ = lambda self : None;
SQMHeaders_swigregister = _libpythonwebserver_framework.SQMHeaders_swigregister
SQMHeaders_swigregister(SQMHeaders)

def get_ip_str(*args):
  return _libpythonwebserver_framework.get_ip_str(*args)
get_ip_str = _libpythonwebserver_framework.get_ip_str

NOT_FOUND_ERROR = _libpythonwebserver_framework.NOT_FOUND_ERROR
METHOD_ERROR = _libpythonwebserver_framework.METHOD_ERROR
NOT_METHOD_ERROR = _libpythonwebserver_framework.NOT_METHOD_ERROR
GENERIC_ERROR = _libpythonwebserver_framework.GENERIC_ERROR
DEFAULT_DROP_WS_PORT = _libpythonwebserver_framework.DEFAULT_DROP_WS_PORT
DEFAULT_DROP_WS_TIMEOUT = _libpythonwebserver_framework.DEFAULT_DROP_WS_TIMEOUT
class HttpEndpoint(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HttpEndpoint, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HttpEndpoint, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _libpythonwebserver_framework.new_HttpEndpoint(*args)
        try: self.this.append(this)
        except: self.this = this
    def __lt__(self, *args): return _libpythonwebserver_framework.HttpEndpoint___lt__(self, *args)
    def match(self, *args): return _libpythonwebserver_framework.HttpEndpoint_match(self, *args)
    def get_url_pars(self): return _libpythonwebserver_framework.HttpEndpoint_get_url_pars(self)
    def get_url_pieces(self): return _libpythonwebserver_framework.HttpEndpoint_get_url_pieces(self)
    def get_chunk_positions(self): return _libpythonwebserver_framework.HttpEndpoint_get_chunk_positions(self)
    __swig_destroy__ = _libpythonwebserver_framework.delete_HttpEndpoint
    __del__ = lambda self : None;
HttpEndpoint_swigregister = _libpythonwebserver_framework.HttpEndpoint_swigregister
HttpEndpoint_swigregister(HttpEndpoint)

class HttpRequest(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HttpRequest, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HttpRequest, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _libpythonwebserver_framework.new_HttpRequest(*args)
        try: self.this.append(this)
        except: self.this = this
    def getUser(self): return _libpythonwebserver_framework.HttpRequest_getUser(self)
    def getPass(self): return _libpythonwebserver_framework.HttpRequest_getPass(self)
    def getPath(self): return _libpythonwebserver_framework.HttpRequest_getPath(self)
    def getPathPieces(self): return _libpythonwebserver_framework.HttpRequest_getPathPieces(self)
    def getPathPiecesSize(self): return _libpythonwebserver_framework.HttpRequest_getPathPiecesSize(self)
    def getPathPiece(self, *args): return _libpythonwebserver_framework.HttpRequest_getPathPiece(self, *args)
    def getMethod(self): return _libpythonwebserver_framework.HttpRequest_getMethod(self)
    def getHeaders(self): return _libpythonwebserver_framework.HttpRequest_getHeaders(self)
    def getFooters(self): return _libpythonwebserver_framework.HttpRequest_getFooters(self)
    def getArgs(self): return _libpythonwebserver_framework.HttpRequest_getArgs(self)
    def getHeader(self, *args): return _libpythonwebserver_framework.HttpRequest_getHeader(self, *args)
    def getFooter(self, *args): return _libpythonwebserver_framework.HttpRequest_getFooter(self, *args)
    def getArg(self, *args): return _libpythonwebserver_framework.HttpRequest_getArg(self, *args)
    def getContent(self): return _libpythonwebserver_framework.HttpRequest_getContent(self)
    def getVersion(self): return _libpythonwebserver_framework.HttpRequest_getVersion(self)
    def getRequestor(self): return _libpythonwebserver_framework.HttpRequest_getRequestor(self)
    def getRequestorPort(self): return _libpythonwebserver_framework.HttpRequest_getRequestorPort(self)
    def setHeader(self, *args): return _libpythonwebserver_framework.HttpRequest_setHeader(self, *args)
    def setFooter(self, *args): return _libpythonwebserver_framework.HttpRequest_setFooter(self, *args)
    def setArg(self, *args): return _libpythonwebserver_framework.HttpRequest_setArg(self, *args)
    def setContent(self, *args): return _libpythonwebserver_framework.HttpRequest_setContent(self, *args)
    def growContent(self, *args): return _libpythonwebserver_framework.HttpRequest_growContent(self, *args)
    def setPath(self, *args): return _libpythonwebserver_framework.HttpRequest_setPath(self, *args)
    def setMethod(self, *args): return _libpythonwebserver_framework.HttpRequest_setMethod(self, *args)
    def setVersion(self, *args): return _libpythonwebserver_framework.HttpRequest_setVersion(self, *args)
    def setRequestor(self, *args): return _libpythonwebserver_framework.HttpRequest_setRequestor(self, *args)
    def setRequestorPort(self, *args): return _libpythonwebserver_framework.HttpRequest_setRequestorPort(self, *args)
    def removeHeader(self, *args): return _libpythonwebserver_framework.HttpRequest_removeHeader(self, *args)
    def setHeaders(self, *args): return _libpythonwebserver_framework.HttpRequest_setHeaders(self, *args)
    def setFooters(self, *args): return _libpythonwebserver_framework.HttpRequest_setFooters(self, *args)
    def setArgs(self, *args): return _libpythonwebserver_framework.HttpRequest_setArgs(self, *args)
    def setUser(self, *args): return _libpythonwebserver_framework.HttpRequest_setUser(self, *args)
    def setPass(self, *args): return _libpythonwebserver_framework.HttpRequest_setPass(self, *args)
    __swig_destroy__ = _libpythonwebserver_framework.delete_HttpRequest
    __del__ = lambda self : None;
HttpRequest_swigregister = _libpythonwebserver_framework.HttpRequest_swigregister
HttpRequest_swigregister(HttpRequest)

class HttpResponse(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HttpResponse, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HttpResponse, name)
    __repr__ = _swig_repr
    STRING_CONTENT = _libpythonwebserver_framework.HttpResponse_STRING_CONTENT
    FILE_CONTENT = _libpythonwebserver_framework.HttpResponse_FILE_CONTENT
    def HttpResponseInit(self, *args): return _libpythonwebserver_framework.HttpResponse_HttpResponseInit(self, *args)
    def __init__(self, *args): 
        this = _libpythonwebserver_framework.new_HttpResponse(*args)
        try: self.this.append(this)
        except: self.this = this
    def getContent(self): return _libpythonwebserver_framework.HttpResponse_getContent(self)
    def setContent(self, *args): return _libpythonwebserver_framework.HttpResponse_setContent(self, *args)
    def getHeader(self, *args): return _libpythonwebserver_framework.HttpResponse_getHeader(self, *args)
    def getFooter(self, *args): return _libpythonwebserver_framework.HttpResponse_getFooter(self, *args)
    def setHeader(self, *args): return _libpythonwebserver_framework.HttpResponse_setHeader(self, *args)
    def setFooter(self, *args): return _libpythonwebserver_framework.HttpResponse_setFooter(self, *args)
    def setContentType(self, *args): return _libpythonwebserver_framework.HttpResponse_setContentType(self, *args)
    def removeHeader(self, *args): return _libpythonwebserver_framework.HttpResponse_removeHeader(self, *args)
    def getHeaders(self): return _libpythonwebserver_framework.HttpResponse_getHeaders(self)
    def getFooters(self): return _libpythonwebserver_framework.HttpResponse_getFooters(self)
    def setHeaders(self, *args): return _libpythonwebserver_framework.HttpResponse_setHeaders(self, *args)
    def setFooters(self, *args): return _libpythonwebserver_framework.HttpResponse_setFooters(self, *args)
    def setResponseCode(self, *args): return _libpythonwebserver_framework.HttpResponse_setResponseCode(self, *args)
    def getResponseCode(self): return _libpythonwebserver_framework.HttpResponse_getResponseCode(self)
    __swig_destroy__ = _libpythonwebserver_framework.delete_HttpResponse
    __del__ = lambda self : None;
HttpResponse_swigregister = _libpythonwebserver_framework.HttpResponse_swigregister
HttpResponse_swigregister(HttpResponse)

class HttpResource(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HttpResource, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HttpResource, name)
    __repr__ = _swig_repr
    def __init__(self): 
        if self.__class__ == HttpResource:
            _self = None
        else:
            _self = self
        this = _libpythonwebserver_framework.new_HttpResource(_self, )
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libpythonwebserver_framework.delete_HttpResource
    __del__ = lambda self : None;
    def render(self, *args): return _libpythonwebserver_framework.HttpResource_render(self, *args)
    def render_404(self): return _libpythonwebserver_framework.HttpResource_render_404(self)
    def render_500(self): return _libpythonwebserver_framework.HttpResource_render_500(self)
    def render_405(self): return _libpythonwebserver_framework.HttpResource_render_405(self)
    def render_GET(self, *args): return _libpythonwebserver_framework.HttpResource_render_GET(self, *args)
    def render_POST(self, *args): return _libpythonwebserver_framework.HttpResource_render_POST(self, *args)
    def render_PUT(self, *args): return _libpythonwebserver_framework.HttpResource_render_PUT(self, *args)
    def render_HEAD(self, *args): return _libpythonwebserver_framework.HttpResource_render_HEAD(self, *args)
    def render_DELETE(self, *args): return _libpythonwebserver_framework.HttpResource_render_DELETE(self, *args)
    def render_TRACE(self, *args): return _libpythonwebserver_framework.HttpResource_render_TRACE(self, *args)
    def render_OPTIONS(self, *args): return _libpythonwebserver_framework.HttpResource_render_OPTIONS(self, *args)
    def render_CONNECT(self, *args): return _libpythonwebserver_framework.HttpResource_render_CONNECT(self, *args)
    def routeRequest(self, *args): return _libpythonwebserver_framework.HttpResource_routeRequest(self, *args)
    def setAllowing(self, *args): return _libpythonwebserver_framework.HttpResource_setAllowing(self, *args)
    def allowAll(self): return _libpythonwebserver_framework.HttpResource_allowAll(self)
    def disallowAll(self): return _libpythonwebserver_framework.HttpResource_disallowAll(self)
    def isAllowed(self, *args): return _libpythonwebserver_framework.HttpResource_isAllowed(self, *args)
    def __disown__(self):
        self.this.disown()
        _libpythonwebserver_framework.disown_HttpResource(self)
        return weakref_proxy(self)
HttpResource_swigregister = _libpythonwebserver_framework.HttpResource_swigregister
HttpResource_swigregister(HttpResource)

class LoggingDelegate(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LoggingDelegate, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LoggingDelegate, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _libpythonwebserver_framework.new_LoggingDelegate()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libpythonwebserver_framework.delete_LoggingDelegate
    __del__ = lambda self : None;
    def log_access(self, *args): return _libpythonwebserver_framework.LoggingDelegate_log_access(self, *args)
    def log_error(self, *args): return _libpythonwebserver_framework.LoggingDelegate_log_error(self, *args)
LoggingDelegate_swigregister = _libpythonwebserver_framework.LoggingDelegate_swigregister
LoggingDelegate_swigregister(LoggingDelegate)

class RequestValidator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RequestValidator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RequestValidator, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _libpythonwebserver_framework.new_RequestValidator()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libpythonwebserver_framework.delete_RequestValidator
    __del__ = lambda self : None;
    def validate(self, *args): return _libpythonwebserver_framework.RequestValidator_validate(self, *args)
RequestValidator_swigregister = _libpythonwebserver_framework.RequestValidator_swigregister
RequestValidator_swigregister(RequestValidator)

class Unescaper(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Unescaper, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Unescaper, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _libpythonwebserver_framework.new_Unescaper()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libpythonwebserver_framework.delete_Unescaper
    __del__ = lambda self : None;
    def unescape(self, *args): return _libpythonwebserver_framework.Unescaper_unescape(self, *args)
Unescaper_swigregister = _libpythonwebserver_framework.Unescaper_swigregister
Unescaper_swigregister(Unescaper)

class Webserver(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Webserver, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Webserver, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _libpythonwebserver_framework.new_Webserver(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libpythonwebserver_framework.delete_Webserver
    __del__ = lambda self : None;
    def start(self, blocking = False): return _libpythonwebserver_framework.Webserver_start(self, blocking)
    def stop(self): return _libpythonwebserver_framework.Webserver_stop(self)
    def isRunning(self): return _libpythonwebserver_framework.Webserver_isRunning(self)
    def registerResource(self, *args): return _libpythonwebserver_framework.Webserver_registerResource(self, *args)
    def sweetKill(self): return _libpythonwebserver_framework.Webserver_sweetKill(self)
Webserver_swigregister = _libpythonwebserver_framework.Webserver_swigregister
Webserver_swigregister(Webserver)

class ModdedRequest(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ModdedRequest, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ModdedRequest, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pp"] = _libpythonwebserver_framework.ModdedRequest_pp_set
    __swig_getmethods__["pp"] = _libpythonwebserver_framework.ModdedRequest_pp_get
    if _newclass:pp = _swig_property(_libpythonwebserver_framework.ModdedRequest_pp_get, _libpythonwebserver_framework.ModdedRequest_pp_set)
    __swig_setmethods__["completeUri"] = _libpythonwebserver_framework.ModdedRequest_completeUri_set
    __swig_getmethods__["completeUri"] = _libpythonwebserver_framework.ModdedRequest_completeUri_get
    if _newclass:completeUri = _swig_property(_libpythonwebserver_framework.ModdedRequest_completeUri_get, _libpythonwebserver_framework.ModdedRequest_completeUri_set)
    __swig_setmethods__["dhr"] = _libpythonwebserver_framework.ModdedRequest_dhr_set
    __swig_getmethods__["dhr"] = _libpythonwebserver_framework.ModdedRequest_dhr_get
    if _newclass:dhr = _swig_property(_libpythonwebserver_framework.ModdedRequest_dhr_get, _libpythonwebserver_framework.ModdedRequest_dhr_set)
    __swig_setmethods__["second"] = _libpythonwebserver_framework.ModdedRequest_second_set
    __swig_getmethods__["second"] = _libpythonwebserver_framework.ModdedRequest_second_get
    if _newclass:second = _swig_property(_libpythonwebserver_framework.ModdedRequest_second_get, _libpythonwebserver_framework.ModdedRequest_second_set)
    def __init__(self): 
        this = _libpythonwebserver_framework.new_ModdedRequest()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libpythonwebserver_framework.delete_ModdedRequest
    __del__ = lambda self : None;
ModdedRequest_swigregister = _libpythonwebserver_framework.ModdedRequest_swigregister
ModdedRequest_swigregister(ModdedRequest)

# This file is compatible with both classic and new-style classes.


