/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_libpythonwebserver_framework_WRAP_H_
#define SWIG_libpythonwebserver_framework_WRAP_H_

#include <map>
#include <string>


class SwigDirector_HttpResource : public HttpResource, public Swig::Director {

public:
    SwigDirector_HttpResource(PyObject *self);
    virtual ~SwigDirector_HttpResource();
    virtual HttpResponse render(HttpRequest const &req);
    virtual HttpResponse render_404();
    virtual HttpResponse render_500();
    virtual HttpResponse render_405();
    virtual HttpResponse render_GET(HttpRequest const &req);
    virtual HttpResponse render_POST(HttpRequest const &req);
    virtual HttpResponse render_PUT(HttpRequest const &req);
    virtual HttpResponse render_HEAD(HttpRequest const &req);
    virtual HttpResponse render_DELETE(HttpRequest const &req);
    virtual HttpResponse render_TRACE(HttpRequest const &req);
    virtual HttpResponse render_OPTIONS(HttpRequest const &req);
    virtual HttpResponse render_CONNECT(HttpRequest const &req);
    virtual HttpResponse routeRequest(HttpRequest const &req);


/* Internal Director utilities */
public:
    bool swig_get_inner(const char* swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }

    void swig_set_inner(const char* swig_protected_method_name, bool val) const
    { swig_inner[swig_protected_method_name] = val;}

private:
    mutable std::map<std::string, bool> swig_inner;


#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class HttpResource doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      };
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[13];
#endif

};


#endif
